version: '3.0'
services:
   db:
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: maintenanceTasks
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
    restart: always
   app:
     depends_on:
       - db
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - "5000:5000"
       - "5001:5001"
     restart: always
volumes:
    dbdata: