version: '3.0'
services:
   db:
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: appDb
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
    restart: always
   app:
     depends_on:
       - db
       - rabbitmq
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - "5000:5000"
     restart: always
   rabbitmq:
     image: rabbitmq:3-management
     hostname: "rabbitmq"
     labels:
         NAME: "rabbitmq"
     ports:
       - "4369:4369"
       - "5671:5671"
       - "5672:5672"
       - "25672:25672"
       - "15671:15671"
       - "15672:15672"
volumes:
    dbdata: